version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./:/home/caesars_ui/app
      - /home/caesars_ui/app/node_modules
    container_name: ts-caesars-docker_ui
    expose:
      - 3000
    ports:
      - 3000:3000
    command: yarn start
    